version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_matching
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./order-matching-backend
    container_name: backend
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mysql
      - redis
    environment:
      - NODE_ENV=development
      - JWT_SECRET=secret
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_DATABASE=order_matching
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  frontend:
    build:
      context: ./order-matching-frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
